INSERT INTO notes (title, content) VALUES
('Note 1', 'Content of Note 1'),
('Note 2', 'Content of Note 2'),
('Note 3', 'Content of Note 3'),
('Note 4', 'Content of Note 4'),
('Note 5', 'Content of Note 5'),
('Note 6', 'Content of Note 6'),
('Note 7', 'Content of Note 7'),
('Note 8', 'Content of Note 8'),
('Note 9', 'Content of Note 9'),
('Note 10', 'Content of Note 10');